export type SP500Entry = {
  symbol: string;
  name: string;
  sector: string;
};

export const SP500_SECTORS = [
  "Technology",
  "Healthcare",
  "Financials",
  "Consumer Discretionary",
  "Communication Services",
  "Industrials",
  "Consumer Staples",
  "Energy",
  "Utilities",
  "Real Estate",
  "Materials",
] as const;

export type SP500Sector = (typeof SP500_SECTORS)[number];

export const SP500_TICKERS: SP500Entry[] = [
  // ── Technology ──
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corp.", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA Corp.", sector: "Technology" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corp.", sector: "Technology" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { symbol: "IBM", name: "IBM Corp.", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology" },
  { symbol: "MU", name: "Micron Technology", sector: "Technology" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technology" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technology" },
  { symbol: "KLAC", name: "KLA Corp.", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", sector: "Technology" },
  { symbol: "INTC", name: "Intel Corp.", sector: "Technology" },
  { symbol: "APH", name: "Amphenol Corp.", sector: "Technology" },
  { symbol: "MSI", name: "Motorola Solutions", sector: "Technology" },
  { symbol: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { symbol: "ROP", name: "Roper Technologies", sector: "Technology" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Technology" },
  { symbol: "DELL", name: "Dell Technologies", sector: "Technology" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Technology" },
  { symbol: "CTSH", name: "Cognizant Technology", sector: "Technology" },
  { symbol: "HPQ", name: "HP Inc.", sector: "Technology" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Technology" },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Technology" },
  { symbol: "CDW", name: "CDW Corp.", sector: "Technology" },
  { symbol: "ANSS", name: "Ansys Inc.", sector: "Technology" },
  { symbol: "FSLR", name: "First Solar Inc.", sector: "Technology" },
  { symbol: "TDY", name: "Teledyne Technologies", sector: "Technology" },
  { symbol: "ZBRA", name: "Zebra Technologies", sector: "Technology" },
  { symbol: "SMCI", name: "Super Micro Computer", sector: "Technology" },
  { symbol: "GEN", name: "Gen Digital Inc.", sector: "Technology" },
  { symbol: "TRMB", name: "Trimble Inc.", sector: "Technology" },
  { symbol: "PTC", name: "PTC Inc.", sector: "Technology" },
  { symbol: "TER", name: "Teradyne Inc.", sector: "Technology" },
  { symbol: "SWKS", name: "Skyworks Solutions", sector: "Technology" },
  { symbol: "EPAM", name: "EPAM Systems", sector: "Technology" },
  { symbol: "JNPR", name: "Juniper Networks", sector: "Technology" },
  { symbol: "FFIV", name: "F5 Inc.", sector: "Technology" },
  { symbol: "QRVO", name: "Qorvo Inc.", sector: "Technology" },
  { symbol: "ENPH", name: "Enphase Energy", sector: "Technology" },
  // ── Healthcare ──
  { symbol: "LLY", name: "Eli Lilly & Co.", sector: "Healthcare" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher Corp.", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "SYK", name: "Stryker Corp.", sector: "Healthcare" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna Group", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" },
  { symbol: "MCK", name: "McKesson Corp.", sector: "Healthcare" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Healthcare" },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Healthcare" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Healthcare" },
  { symbol: "A", name: "Agilent Technologies", sector: "Healthcare" },
  { symbol: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare" },
  { symbol: "IQV", name: "IQVIA Holdings", sector: "Healthcare" },
  { symbol: "MTD", name: "Mettler-Toledo", sector: "Healthcare" },
  { symbol: "DXCM", name: "DexCom Inc.", sector: "Healthcare" },
  { symbol: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
  { symbol: "BAX", name: "Baxter International", sector: "Healthcare" },
  { symbol: "GEHC", name: "GE HealthCare", sector: "Healthcare" },
  { symbol: "COR", name: "Cencora Inc.", sector: "Healthcare" },
  { symbol: "ALGN", name: "Align Technology", sector: "Healthcare" },
  { symbol: "HOLX", name: "Hologic Inc.", sector: "Healthcare" },
  { symbol: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
  { symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { symbol: "ILMN", name: "Illumina Inc.", sector: "Healthcare" },
  { symbol: "PODD", name: "Insulet Corp.", sector: "Healthcare" },
  { symbol: "VTRS", name: "Viatris Inc.", sector: "Healthcare" },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Healthcare" },
  { symbol: "TECH", name: "Bio-Techne Corp.", sector: "Healthcare" },
  { symbol: "INCY", name: "Incyte Corp.", sector: "Healthcare" },
  { symbol: "MOH", name: "Molina Healthcare", sector: "Healthcare" },
  { symbol: "RVTY", name: "Revvity Inc.", sector: "Healthcare" },
  { symbol: "HSIC", name: "Henry Schein", sector: "Healthcare" },
  { symbol: "CTLT", name: "Catalent Inc.", sector: "Healthcare" },
  { symbol: "DVA", name: "DaVita Inc.", sector: "Healthcare" },
  // ── Financials ──
  { symbol: "BRK-B", name: "Berkshire Hathaway", sector: "Financials" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo & Co.", sector: "Financials" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "CB", name: "Chubb Ltd.", sector: "Financials" },
  { symbol: "PGR", name: "Progressive Corp.", sector: "Financials" },
  { symbol: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { symbol: "AON", name: "Aon plc", sector: "Financials" },
  { symbol: "CME", name: "CME Group", sector: "Financials" },
  { symbol: "USB", name: "US Bancorp", sector: "Financials" },
  { symbol: "PNC", name: "PNC Financial", sector: "Financials" },
  { symbol: "MCO", name: "Moody's Corp.", sector: "Financials" },
  { symbol: "TFC", name: "Truist Financial", sector: "Financials" },
  { symbol: "AJG", name: "Arthur J. Gallagher", sector: "Financials" },
  { symbol: "MET", name: "MetLife Inc.", sector: "Financials" },
  { symbol: "AIG", name: "American Intl Group", sector: "Financials" },
  { symbol: "AFL", name: "Aflac Inc.", sector: "Financials" },
  { symbol: "TRV", name: "Travelers Companies", sector: "Financials" },
  { symbol: "ALL", name: "Allstate Corp.", sector: "Financials" },
  { symbol: "BK", name: "Bank of New York Mellon", sector: "Financials" },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financials" },
  { symbol: "STT", name: "State Street Corp.", sector: "Financials" },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Financials" },
  { symbol: "FIS", name: "Fidelity National Info", sector: "Financials" },
  { symbol: "TROW", name: "T. Rowe Price", sector: "Financials" },
  { symbol: "COF", name: "Capital One Financial", sector: "Financials" },
  { symbol: "DFS", name: "Discover Financial", sector: "Financials" },
  { symbol: "HBAN", name: "Huntington Bancshares", sector: "Financials" },
  { symbol: "MTB", name: "M&T Bank Corp.", sector: "Financials" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", sector: "Financials" },
  { symbol: "CINF", name: "Cincinnati Financial", sector: "Financials" },
  { symbol: "RF", name: "Regions Financial", sector: "Financials" },
  { symbol: "CFG", name: "Citizens Financial", sector: "Financials" },
  { symbol: "KEY", name: "KeyCorp", sector: "Financials" },
  { symbol: "FRC", name: "First Republic Bank", sector: "Financials" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Financials" },
  { symbol: "RJF", name: "Raymond James Financial", sector: "Financials" },
  { symbol: "WRB", name: "W.R. Berkley Corp.", sector: "Financials" },
  { symbol: "BEN", name: "Franklin Resources", sector: "Financials" },
  { symbol: "IVZ", name: "Invesco Ltd.", sector: "Financials" },
  { symbol: "GL", name: "Globe Life Inc.", sector: "Financials" },
  { symbol: "RE", name: "Everest Group", sector: "Financials" },
  { symbol: "L", name: "Loews Corp.", sector: "Financials" },
  { symbol: "ACGL", name: "Arch Capital Group", sector: "Financials" },
  // ── Consumer Discretionary ──
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { symbol: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary" },
  { symbol: "MCD", name: "McDonald's Corp.", sector: "Consumer Discretionary" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { symbol: "LOW", name: "Lowe's Companies", sector: "Consumer Discretionary" },
  { symbol: "SBUX", name: "Starbucks Corp.", sector: "Consumer Discretionary" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { symbol: "ABNB", name: "Airbnb Inc.", sector: "Consumer Discretionary" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { symbol: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { symbol: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { symbol: "DHI", name: "D.R. Horton", sector: "Consumer Discretionary" },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { symbol: "F", name: "Ford Motor Co.", sector: "Consumer Discretionary" },
  { symbol: "LEN", name: "Lennar Corp.", sector: "Consumer Discretionary" },
  { symbol: "PHM", name: "PulteGroup Inc.", sector: "Consumer Discretionary" },
  { symbol: "RCL", name: "Royal Caribbean", sector: "Consumer Discretionary" },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary" },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
  { symbol: "DKNG", name: "DraftKings Inc.", sector: "Consumer Discretionary" },
  { symbol: "APTV", name: "Aptiv plc", sector: "Consumer Discretionary" },
  { symbol: "GRMN", name: "Garmin Ltd.", sector: "Consumer Discretionary" },
  { symbol: "POOL", name: "Pool Corp.", sector: "Consumer Discretionary" },
  { symbol: "DPZ", name: "Domino's Pizza", sector: "Consumer Discretionary" },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Consumer Discretionary" },
  { symbol: "DECK", name: "Deckers Outdoor", sector: "Consumer Discretionary" },
  { symbol: "BBY", name: "Best Buy Co.", sector: "Consumer Discretionary" },
  { symbol: "EXPE", name: "Expedia Group", sector: "Consumer Discretionary" },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary" },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary" },
  { symbol: "CCL", name: "Carnival Corp.", sector: "Consumer Discretionary" },
  { symbol: "TPR", name: "Tapestry Inc.", sector: "Consumer Discretionary" },
  { symbol: "BWA", name: "BorgWarner Inc.", sector: "Consumer Discretionary" },
  { symbol: "CZR", name: "Caesars Entertainment", sector: "Consumer Discretionary" },
  { symbol: "HAS", name: "Hasbro Inc.", sector: "Consumer Discretionary" },
  { symbol: "MHK", name: "Mohawk Industries", sector: "Consumer Discretionary" },
  { symbol: "NVR", name: "NVR Inc.", sector: "Consumer Discretionary" },
  { symbol: "GPC", name: "Genuine Parts Co.", sector: "Consumer Discretionary" },
  { symbol: "ETSY", name: "Etsy Inc.", sector: "Consumer Discretionary" },
  // ── Communication Services ──
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Communication Services" },
  { symbol: "GOOGL", name: "Alphabet Inc. (A)", sector: "Communication Services" },
  { symbol: "GOOG", name: "Alphabet Inc. (C)", sector: "Communication Services" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { symbol: "DIS", name: "Walt Disney Co.", sector: "Communication Services" },
  { symbol: "CMCSA", name: "Comcast Corp.", sector: "Communication Services" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { symbol: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { symbol: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { symbol: "EA", name: "Electronic Arts", sector: "Communication Services" },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Communication Services" },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services" },
  { symbol: "OMC", name: "Omnicom Group", sector: "Communication Services" },
  { symbol: "IPG", name: "Interpublic Group", sector: "Communication Services" },
  { symbol: "MTCH", name: "Match Group", sector: "Communication Services" },
  { symbol: "LYV", name: "Live Nation Entertainment", sector: "Communication Services" },
  { symbol: "PARA", name: "Paramount Global", sector: "Communication Services" },
  { symbol: "FOXA", name: "Fox Corp. (A)", sector: "Communication Services" },
  { symbol: "NWS", name: "News Corp.", sector: "Communication Services" },
  // ── Industrials ──
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { symbol: "RTX", name: "RTX Corp.", sector: "Industrials" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrials" },
  { symbol: "HON", name: "Honeywell International", sector: "Industrials" },
  { symbol: "BA", name: "Boeing Co.", sector: "Industrials" },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { symbol: "DE", name: "Deere & Co.", sector: "Industrials" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Industrials" },
  { symbol: "ETN", name: "Eaton Corp.", sector: "Industrials" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrials" },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrials" },
  { symbol: "WM", name: "Waste Management", sector: "Industrials" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrials" },
  { symbol: "FDX", name: "FedEx Corp.", sector: "Industrials" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrials" },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrials" },
  { symbol: "CSX", name: "CSX Corp.", sector: "Industrials" },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrials" },
  { symbol: "CARR", name: "Carrier Global", sector: "Industrials" },
  { symbol: "TT", name: "Trane Technologies", sector: "Industrials" },
  { symbol: "GWW", name: "W.W. Grainger", sector: "Industrials" },
  { symbol: "CTAS", name: "Cintas Corp.", sector: "Industrials" },
  { symbol: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
  { symbol: "FAST", name: "Fastenal Co.", sector: "Industrials" },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrials" },
  { symbol: "AME", name: "AMETEK Inc.", sector: "Industrials" },
  { symbol: "RSG", name: "Republic Services", sector: "Industrials" },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Industrials" },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrials" },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrials" },
  { symbol: "CPRT", name: "Copart Inc.", sector: "Industrials" },
  { symbol: "PAYX", name: "Paychex Inc.", sector: "Industrials" },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrials" },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials" },
  { symbol: "HUBB", name: "Hubbell Inc.", sector: "Industrials" },
  { symbol: "DOV", name: "Dover Corp.", sector: "Industrials" },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrials" },
  { symbol: "IEX", name: "IDEX Corp.", sector: "Industrials" },
  { symbol: "GPN", name: "Global Payments", sector: "Industrials" },
  { symbol: "WAB", name: "Westinghouse Air Brake", sector: "Industrials" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrials" },
  { symbol: "UAL", name: "United Airlines", sector: "Industrials" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrials" },
  // ── Consumer Staples ──
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer Staples" },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { symbol: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { symbol: "MO", name: "Altria Group", sector: "Consumer Staples" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples" },
  { symbol: "EL", name: "Estee Lauder", sector: "Consumer Staples" },
  { symbol: "STZ", name: "Constellation Brands", sector: "Consumer Staples" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", sector: "Consumer Staples" },
  { symbol: "SYY", name: "Sysco Corp.", sector: "Consumer Staples" },
  { symbol: "GIS", name: "General Mills", sector: "Consumer Staples" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples" },
  { symbol: "HSY", name: "Hershey Co.", sector: "Consumer Staples" },
  { symbol: "K", name: "Kellanova", sector: "Consumer Staples" },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples" },
  { symbol: "KR", name: "Kroger Co.", sector: "Consumer Staples" },
  { symbol: "MNST", name: "Monster Beverage", sector: "Consumer Staples" },
  { symbol: "MKC", name: "McCormick & Co.", sector: "Consumer Staples" },
  { symbol: "CHD", name: "Church & Dwight", sector: "Consumer Staples" },
  { symbol: "CLX", name: "Clorox Co.", sector: "Consumer Staples" },
  { symbol: "SJM", name: "J.M. Smucker Co.", sector: "Consumer Staples" },
  { symbol: "TSN", name: "Tyson Foods", sector: "Consumer Staples" },
  { symbol: "HRL", name: "Hormel Foods", sector: "Consumer Staples" },
  { symbol: "CAG", name: "Conagra Brands", sector: "Consumer Staples" },
  { symbol: "CPB", name: "Campbell Soup", sector: "Consumer Staples" },
  { symbol: "BG", name: "Bunge Ltd.", sector: "Consumer Staples" },
  { symbol: "TAP", name: "Molson Coors", sector: "Consumer Staples" },
  // ── Energy ──
  { symbol: "XOM", name: "Exxon Mobil Corp.", sector: "Energy" },
  { symbol: "CVX", name: "Chevron Corp.", sector: "Energy" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "EOG", name: "EOG Resources", sector: "Energy" },
  { symbol: "SLB", name: "Schlumberger Ltd.", sector: "Energy" },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energy" },
  { symbol: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy" },
  { symbol: "VLO", name: "Valero Energy", sector: "Energy" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { symbol: "WMB", name: "Williams Companies", sector: "Energy" },
  { symbol: "HES", name: "Hess Corp.", sector: "Energy" },
  { symbol: "HAL", name: "Halliburton Co.", sector: "Energy" },
  { symbol: "DVN", name: "Devon Energy", sector: "Energy" },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energy" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energy" },
  { symbol: "OKE", name: "ONEOK Inc.", sector: "Energy" },
  { symbol: "TRGP", name: "Targa Resources", sector: "Energy" },
  { symbol: "CTRA", name: "Coterra Energy", sector: "Energy" },
  { symbol: "EQT", name: "EQT Corp.", sector: "Energy" },
  { symbol: "MRO", name: "Marathon Oil", sector: "Energy" },
  { symbol: "APA", name: "APA Corp.", sector: "Energy" },
  // ── Utilities ──
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities" },
  { symbol: "SO", name: "Southern Co.", sector: "Utilities" },
  { symbol: "D", name: "Dominion Energy", sector: "Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities" },
  { symbol: "SRE", name: "Sempra", sector: "Utilities" },
  { symbol: "EXC", name: "Exelon Corp.", sector: "Utilities" },
  { symbol: "XEL", name: "Xcel Energy", sector: "Utilities" },
  { symbol: "ED", name: "Consolidated Edison", sector: "Utilities" },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Utilities" },
  { symbol: "PCG", name: "PG&E Corp.", sector: "Utilities" },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities" },
  { symbol: "AWK", name: "American Water Works", sector: "Utilities" },
  { symbol: "EIX", name: "Edison International", sector: "Utilities" },
  { symbol: "DTE", name: "DTE Energy", sector: "Utilities" },
  { symbol: "FE", name: "FirstEnergy Corp.", sector: "Utilities" },
  { symbol: "PPL", name: "PPL Corp.", sector: "Utilities" },
  { symbol: "AEE", name: "Ameren Corp.", sector: "Utilities" },
  { symbol: "CMS", name: "CMS Energy", sector: "Utilities" },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities" },
  { symbol: "EVRG", name: "Evergy Inc.", sector: "Utilities" },
  { symbol: "ATO", name: "Atmos Energy", sector: "Utilities" },
  { symbol: "LNT", name: "Alliant Energy", sector: "Utilities" },
  { symbol: "NI", name: "NiSource Inc.", sector: "Utilities" },
  { symbol: "PNW", name: "Pinnacle West Capital", sector: "Utilities" },
  // ── Real Estate ──
  { symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate" },
  { symbol: "CCI", name: "Crown Castle", sector: "Real Estate" },
  { symbol: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate" },
  { symbol: "O", name: "Realty Income", sector: "Real Estate" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
  { symbol: "DLR", name: "Digital Realty", sector: "Real Estate" },
  { symbol: "VICI", name: "VICI Properties", sector: "Real Estate" },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "Real Estate" },
  { symbol: "EQR", name: "Equity Residential", sector: "Real Estate" },
  { symbol: "SBAC", name: "SBA Communications", sector: "Real Estate" },
  { symbol: "WY", name: "Weyerhaeuser Co.", sector: "Real Estate" },
  { symbol: "ARE", name: "Alexandria Real Estate", sector: "Real Estate" },
  { symbol: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Real Estate" },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Real Estate" },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Real Estate" },
  { symbol: "VTR", name: "Ventas Inc.", sector: "Real Estate" },
  { symbol: "PEAK", name: "Healthpeak Properties", sector: "Real Estate" },
  { symbol: "KIM", name: "Kimco Realty", sector: "Real Estate" },
  { symbol: "REG", name: "Regency Centers", sector: "Real Estate" },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate" },
  { symbol: "BXP", name: "BXP Inc.", sector: "Real Estate" },
  { symbol: "UDR", name: "UDR Inc.", sector: "Real Estate" },
  { symbol: "IRM", name: "Iron Mountain", sector: "Real Estate" },
  // ── Materials ──
  { symbol: "LIN", name: "Linde plc", sector: "Materials" },
  { symbol: "APD", name: "Air Products & Chemicals", sector: "Materials" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { symbol: "ECL", name: "Ecolab Inc.", sector: "Materials" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Materials" },
  { symbol: "NEM", name: "Newmont Corp.", sector: "Materials" },
  { symbol: "NUE", name: "Nucor Corp.", sector: "Materials" },
  { symbol: "VMC", name: "Vulcan Materials", sector: "Materials" },
  { symbol: "MLM", name: "Martin Marietta", sector: "Materials" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials" },
  { symbol: "DD", name: "DuPont de Nemours", sector: "Materials" },
  { symbol: "PPG", name: "PPG Industries", sector: "Materials" },
  { symbol: "CTVA", name: "Corteva Inc.", sector: "Materials" },
  { symbol: "CF", name: "CF Industries", sector: "Materials" },
  { symbol: "IFF", name: "International Flavors", sector: "Materials" },
  { symbol: "ALB", name: "Albemarle Corp.", sector: "Materials" },
  { symbol: "CE", name: "Celanese Corp.", sector: "Materials" },
  { symbol: "EMN", name: "Eastman Chemical", sector: "Materials" },
  { symbol: "PKG", name: "Packaging Corp.", sector: "Materials" },
  { symbol: "IP", name: "International Paper", sector: "Materials" },
  { symbol: "FMC", name: "FMC Corp.", sector: "Materials" },
  { symbol: "BALL", name: "Ball Corp.", sector: "Materials" },
  { symbol: "AVY", name: "Avery Dennison", sector: "Materials" },
  { symbol: "SEE", name: "Sealed Air Corp.", sector: "Materials" },
  { symbol: "AMCR", name: "Amcor plc", sector: "Materials" },
  { symbol: "MOS", name: "Mosaic Co.", sector: "Materials" },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Materials" },
];
